theme: jekyll-theme-architect
plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:
  - CONTRIBUTING.md
  - README.md
  - index.md
  - bt_bst.md
  - two_pointers.md
  - dp.md
