theme: jekyll-theme-architect
plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:
  - CONTRIBUTING.md
  - README.md
  - index.md
  - bt_bst.md
  - two_pointers.md
  - dp.md
  - string.md
  - bit_manipulation.md
  - stack.md
  - hash_table.md
  - array.md
  - greedy.md
  - dfs_backtracking.md
  - trie.md
  - bfs.md
  - simulation.md
  - priority_queue.md
  - union_find.md
